### ISSUE TITLE
`PostBox` Component

### ISSUE THREAD

**Issue by LeoBorai** [whizzes/nexus#14]
Implement a `PostBox` component which should look like the following:

![2022-04-22 20 55 51](https://user-images.githubusercontent.com/34756077/164844364-310aa9a3-20d8-4399-8190-9a179b29571b.jpg)

And use the `postCreate` mutation from `nexus-api` to create text posts with it.

**Comment by Michael-Liendo** [comment]
Thanks you!

**Comment by LeoBorai** [comment]
This is achieved on #15!
