### ISSUE TITLE
Feature | Signup/Login Page

### ISSUE THREAD

**Issue by dararod** [whizzes/nexus#3]
Implement the Sign up and Login page which will live under `/`.

- [ ] Port Button Component
- [x] Implement Signup Form
- [x] Implement Signup Form with Submit Alert

**Comment by LeoBorai** [comment]
@dararod I've implemented the Login with the same styles that we used for https://github.com/dararod/matefeed on Input component.

![image](https://user-images.githubusercontent.com/34756077/154818900-020eb129-2fbc-48f4-a2a4-3028844ec10f.png)

I leave the Signup to you, you must use the same component with a "toggle" button to switch from Login form to Signup form.

![Screen Shot 2022-02-19 at 5 58 34 PM](https://user-images.githubusercontent.com/34756077/154818926-fa5779dd-67dc-4a0e-9a56-781e02c527df.png)

**Comment by LeoBorai** [comment]
Please, also consider porting the Button component from ReactJS to Svelte as well. https://github.com/dararod/matefeed/tree/main/src/client/components/Button.

If you find yourself in trouble with Tailwind feel free to use a `<style>` tag to define the classes and then we can migrate them together to TailwindCSS.

**Comment by LeoBorai** [comment]
I will close this and open issues for login and signup separately.
