### ISSUE TITLE
Login View

### ISSUE THREAD

**Issue by LeoBorai** [whizzes/nexus#7]
Users must be able to login into their accounts through a login form.
The `userCreate` mutation allows creating a new user with its details, the server with support to this logic is available on: [nexus-server](https://github.com/whizzbit/nexus-server).

The route for this page must be:  `/login`, the background should change on a daily basis and must also show the background picture author from Unsplash. The data that must be shown from the author is:

- Full Name
- Unsplash Avatar
- Username

## Design

![Nexus Login Page](https://user-images.githubusercontent.com/34756077/158086975-6cf717c0-3c1e-4324-afae-f6bc6f79c594.png)

**Comment by LeoBorai** [comment]
Details on how server side implementation is available here: https://github.com/whizzbit/nexus-server/issues/1

**Comment by Michael-Liendo** [comment]
I feel like I can do, can I?

**Comment by LeoBorai** [comment]
> I feel like I can do, can I?

Of course!

**Comment by LeoBorai** [comment]
@Michael-Liendo now that we have a starting point on Input components I believe its a good moment to begin with this feature. Let me know if you need any help!

**Comment by LeoBorai** [comment]
this is already done!
